// data layer until Firebase is added

const products = [
  {
    id: 1,
    name: "Classic Vanilla Sundae",
    category: "sundaes",
    price: 350,
    desc: "Creamy vanilla ice cream topped with hot fudge, whipped cream & a cherry on top.",
    badge: "Best Seller",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=640&q=80&fit=crop",
  },
  {
    id: 2,
    name: "Berry Bliss Sundae",
    category: "sundaes",
    price: 420,
    desc: "Mixed berry compote over vanilla gelato with toasted almonds and a honey drizzle.",
    badge: "",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://plus.unsplash.com/premium_photo-1669680785558-c189b49aed4e?w=640&q=80&fit=crop",
  },
  {
    id: 3,
    name: "Chocolate Lava Sundae",
    category: "sundaes",
    price: 480,
    desc: "Warm molten chocolate sauce poured over two scoops of dark chocolate ice cream.",
    badge: "Popular",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1571089465427-cd3c533e809f?w=640&q=80&fit=crop",
  },
  {
    id: 4,
    name: "Rainbow Sprinkle Sundae",
    category: "sundaes",
    price: 390,
    desc: "Three scoops, rainbow sprinkles, caramel drizzle & crushed wafer biscuits.",
    badge: "Kids Fav",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1576762754073-9397bd6e7f34?w=640&q=80&fit=crop",
  },
  {
    id: 5,
    name: "Red Velvet Cake",
    category: "cakes",
    price: 1800,
    desc: "Moist red velvet layers with silky cream cheese frosting. Available per slice or full.",
    badge: "Signature",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://plus.unsplash.com/premium_photo-1713920189815-876dbdf5f56e?w=640&q=80&fit=crop",
  },
  {
    id: 6,
    name: "Classic Cheesecake",
    category: "cakes",
    price: 1500,
    desc: "New York-style baked cheesecake sitting on a buttery graham cracker crust.",
    badge: "",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=640&q=80&fit=crop",
  },
  {
    id: 7,
    name: "Black Forest Cake",
    category: "cakes",
    price: 2000,
    desc: "Dark chocolate sponge soaked in Kirsch syrup, cherries & whipped cream towers.",
    badge: "Bestseller",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1605807646983-377bc5a76493?w=640&q=80&fit=crop",
  },
  {
    id: 8,
    name: "Lemon Drizzle Cake",
    category: "cakes",
    price: 1400,
    desc: "Light zesty sponge drenched in a tangy lemon glaze. Refreshingly bright.",
    badge: "New",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=640&q=80&fit=crop",
  },
  {
    id: 9,
    name: "Signature Espresso",
    category: "coffees",
    price: 280,
    desc: "Double shot of our house-blend Ethiopian espresso. Bold, complex & perfectly balanced.",
    badge: "",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=640&q=80&fit=crop",
  },
  {
    id: 10,
    name: "Caramel Latte",
    category: "coffees",
    price: 380,
    desc: "Rich espresso with steamed whole milk and housemade salted caramel syrup.",
    badge: "Popular",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1534040385115-33dcb3acba5b?w=640&q=80&fit=crop",
  },
  {
    id: 11,
    name: "Iced Mocha",
    category: "coffees",
    price: 420,
    desc: "Cold brew coffee, dark chocolate sauce & cream — served over crushed ice.",
    badge: "Summer Hit",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=640&q=80&fit=crop",
  },
  {
    id: 12,
    name: "Cinnamon Flat White",
    category: "coffees",
    price: 350,
    desc: "Velvety microfoam espresso finished with a dusting of Sri Lankan cinnamon.",
    badge: "",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=640&q=80&fit=crop",
  },
  {
    id: 13,
    name: "Masala Chai",
    category: "teas",
    price: 220,
    desc: "Slow-brewed black tea with cardamom, ginger, cinnamon sticks & whole milk.",
    badge: "Classic",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=640&q=80&fit=crop",
  },
  {
    id: 14,
    name: "Rose Kashmiri Tea",
    category: "teas",
    price: 300,
    desc: "Delicate pink milk tea with dried rose petals, pistachios & a hint of cardamom.",
    badge: "Signature",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=640&q=80&fit=crop",
  },
  {
    id: 15,
    name: "Mint Green Tea",
    category: "teas",
    price: 260,
    desc: "Premium Japanese green tea brewed with fresh mint leaves. Calming & crisp.",
    badge: "",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=640&q=80&fit=crop",
  },
  {
    id: 16,
    name: "English Breakfast",
    category: "teas",
    price: 240,
    desc: "Full-bodied robust blend served with warm whole milk and unrefined cane sugar.",
    badge: "",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?w=640&q=80&fit=crop",
  },
];
