// data layer until Firebase is added

const products = [
  {
    id: 1,
    name: "Classic Vanilla Sundae",
    category: "sundaes",
    price: 350,
    desc: "Creamy vanilla ice cream topped with hot fudge, whipped cream & a cherry on top.",
    badge: "Best Seller",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=640&q=80&fit=crop",
  },
  {
    id: 2,
    name: "Berry Bliss Sundae",
    category: "sundaes",
    price: 420,
    desc: "Mixed berry compote over vanilla gelato with toasted almonds and a honey drizzle.",
    badge: "",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://plus.unsplash.com/premium_photo-1669680785558-c189b49aed4e?w=640&q=80&fit=crop",
  },
  {
    id: 3,
    name: "Chocolate Lava Sundae",
    category: "sundaes",
    price: 480,
    desc: "Warm molten chocolate sauce poured over two scoops of dark chocolate ice cream.",
    badge: "Popular",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1571089465427-cd3c533e809f?w=640&q=80&fit=crop",
  },
  {
    id: 4,
    name: "Rainbow Sprinkle Sundae",
    category: "sundaes",
    price: 390,
    desc: "Three scoops, rainbow sprinkles, caramel drizzle & crushed wafer biscuits.",
    badge: "Kids Fav",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1560008581-09826d1de69e?w=640&q=80&fit=crop",
  },
  {
    id: 5,
    name: "Red Velvet Cake",
    category: "cakes",
    price: 1800,
    desc: "Moist red velvet layers with silky cream cheese frosting. Available per slice or full.",
    badge: "Signature",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://plus.unsplash.com/premium_photo-1713920189815-876dbdf5f56e?w=640&q=80&fit=crop",
  },
  {
    id: 6,
    name: "Classic Cheesecake",
    category: "cakes",
    price: 1500,
    desc: "New York-style baked cheesecake sitting on a buttery graham cracker crust.",
    badge: "",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=640&q=80&fit=crop",
  },
  {
    id: 7,
    name: "Black Forest Cake",
    category: "cakes",
    price: 2000,
    desc: "Dark chocolate sponge soaked in Kirsch syrup, cherries & whipped cream towers.",
    badge: "Bestseller",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1605807646983-377bc5a76493?w=640&q=80&fit=crop",
  },
  {
    id: 8,
    name: "Lemon Drizzle Cake",
    category: "cakes",
    price: 1400,
    desc: "Light zesty sponge drenched in a tangy lemon glaze. Refreshingly bright.",
    badge: "New",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=640&q=80&fit=crop",
  },
  {
    id: 9,
    name: "Mango Tango Shake",
    category: "shakes",
    price: 320,
    desc: "Fresh mango blended with vanilla ice cream and a hint of chilli for a sweet kick.",
    badge: "Summer Hit",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://plus.unsplash.com/premium_photo-1663091544172-794c537af00c?w=640&q=80&fit=crop",
  },
  {
    id: 10,
    name: "Oreo Overload Shake",
    category: "shakes",
    price: 380,
    desc: "Thick vanilla shake loaded with crushed Oreos, whipped cream and chocolate drizzle.",
    badge: "Best Seller",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1541658016709-82535e94bc69?w=640&q=80&fit=crop",
  },
  {
    id: 11,
    name: "Strawberry Dream Shake",
    category: "shakes",
    price: 350,
    desc: "Fresh strawberries blended with creamy milk and a scoop of strawberry gelato.",
    badge: "",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://plus.unsplash.com/premium_photo-1695927470038-35a215e794f0?w=640&q=80&fit=crop",
  },
  {
    id: 12,
    name: "Dark Chocolate Shake",
    category: "shakes",
    price: 400,
    desc: "Rich 70% dark chocolate melted into cold milk with a salted caramel swirl on top.",
    badge: "Popular",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://plus.unsplash.com/premium_photo-1695750678156-ed7b2ad39980?w=640&q=80&fit=crop",
  },
  {
    id: 13,
    name: "Classic Chocolate Chip",
    category: "cookies",
    price: 180,
    desc: "Buttery soft-baked cookie loaded with semi-sweet chocolate chips. A timeless classic.",
    badge: "Classic",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=640&q=80&fit=crop",
  },
  {
    id: 14,
    name: "Double Fudge Cookie",
    category: "cookies",
    price: 220,
    desc: "Dense, fudgy chocolate cookie with a gooey center and crispy edges. Pure indulgence.",
    badge: "Popular",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://plus.unsplash.com/premium_photo-1666976136060-c9a29fb829b3?w=640&q=80&fit=crop",
  },
  {
    id: 15,
    name: "Nutella Stuffed Cookie",
    category: "cookies",
    price: 260,
    desc: "Golden brown cookie with a warm Nutella-filled center that oozes with every bite.",
    badge: "Signature",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=640&q=80&fit=crop",
  },
  {
    id: 16,
    name: "Oat & Raisin Cookie",
    category: "cookies",
    price: 160,
    desc: "Hearty oat cookie with plump raisins, cinnamon and a chewy golden-baked finish.",
    badge: "",
    inStock: true,
    ratings: [],
    ratedBy: [],
    image:
      "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=640&q=80&fit=crop",
  },
];
